{
 "title": "Weather Station Template BME680",
 "description": "Weather Station Template for BME680  Sensor.",
 "tags": [
  "Weather Station",
  "BME680"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Indoor Air Quality (IAQ) Classification",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\ntimestamp,\r\niaq\r\nFROM  weather_data\r\nWHERE timestamp > dateadd('d', -1, now())"
    }
   ]
  },
  {
   "title": "Indoor Air Quality (IAQ)  Rating",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\ntimestamp,\r\niaq\r\nFROM  weather_data\r\nWHERE timestamp > dateadd('d', -1, now())\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\ntimestamp,\r\ntemperature\r\nFROM  weather_data\r\nWHERE timestamp > dateadd('d', -1, now())\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\ntimestamp,\r\ntemperature\r\nFROM  weather_data\r\nWHERE timestamp > dateadd('d', -1, now())\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\ntimestamp,\r\nhumidity\r\nFROM  weather_data\r\nWHERE timestamp > dateadd('d', -1, now())\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\ntimestamp,\r\nhumidity\r\nFROM  weather_data\r\nWHERE timestamp > dateadd('d', -1, now())\r\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, pressure\r\nFROM  weather_data\r\nWHERE timestamp > dateadd('d', -1, now())\r\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\ntimestamp,\r\npressure\r\nFROM  weather_data\r\nWHERE timestamp > dateadd('d', -1, now())"
    }
   ]
  }
 ]
}