{
 "title": "WeatherLinkIP Weather Station",
 "description": "A dashboard that visualizes weather data captured from WeatherLinkIP-enabled weather stations like the Vantage Vue or Vantage Pro2 weather stations from Davis Instruments.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weatherlink_insideTemperature", "legendFormat": "Indoor Temperature" },
    { "expr": "weatherlink_outsideTemperature", "legendFormat": "Outdoor Temperature" }
   ]
  },
  {
   "title": "Inside Temp/Humidity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "weatherlink_insideTemperature", "legendFormat": "Temp" },
    { "expr": "weatherlink_insideHumidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weatherlink_insideHumidity", "legendFormat": "Indoor Humidity" },
    { "expr": "weatherlink_outsideHumidity", "legendFormat": "Outdoor Humidity" }
   ]
  },
  {
   "title": "Barometer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "weatherlink_barometer", "legendFormat": "Barometer" }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "weatherlink_windDirection" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    { "expr": "weatherlink_windSpeed", "legendFormat": "Wind Speed" }
   ]
  }
 ]
}