{
 "title": "Netatmo Weather Station",
 "tags": [ "influxdb" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Station",
    "query": "show tag values with key = \"station\""
   },
   {
    "name": "Module",
    "query": "show tag values with key = \"module\" WHERE station =~ /$Station/"
   }
  ]
 },
 "panels": [
  {
   "title": "Station",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"height:100%;display:flex;justify-content:center;align-items:center;\">\n<h1 style=\"font-size:250%;font-weight:bold;\">$Station</h1>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timezone",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timezone",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Noise",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "noise",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Noise Level",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "noise",
     "query": "SELECT last(\"noise\") FROM /^$Station$/ WHERE (\"station\" =~ /^$Module$/) AND $timeFilter GROUP BY time(10m), \"module\", \"station\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$Module$/" }
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altitude",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure Trend",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pressure_trend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "$Module",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "Module",
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT last(\"temp\") FROM /^$Station$/ WHERE (\"module\" =~ /^$Module$/ AND \"station\" =~ /^$Station$/) AND $timeFilter GROUP BY time(10m), \"module\", \"station\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "max_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Signal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rf_status",
     "query": "SELECT last(\"value\") *-1 FROM \"rf_status\" WHERE (\"station\" =~ /^$Station$/ AND \"module\" =~ /^$Module$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$Module$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "wifi_status",
     "query": "SELECT last(\"value\") *-1 FROM \"rf_status\" WHERE (\"station\" =~ /^$Station$/ AND \"module\" =~ /^$Module$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$Module$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Trend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "temp_trend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$Module$/" }
     ]
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "min_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  }
 ]
}